models:
  - name: stg_users
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique
          
  - name: fct_daily_revenue
    description: "Aggregated daily revenue from orders with completed payments"
 